version: '3.4'
## https://github.com/cturra/docker-ntp/blob/main/docker-compose.yml
services:
  ntp:
    image: cturra/ntp:latest
    container_name: time
    restart: always
    ports:
      - 123:123/udp
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
